title: No Guff Studio
author: Bubba McGuff
email: noguffstudio@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
 My project is based on the assumption that a market exists for hand printed artwork with a unique aesthetic that screen printing can offer. We can print short runs of art editions, posters, greeting cards, postcards, etc. using thick paper, coloured paper, bright solid ink coverage, metallics, overlapping, and halftones creatively, for example.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
